apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
      - name: backend-service
        image: salimamri/backend-springboot
        ports:
        - containerPort: 8080  
        env:
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://root:password@mongodb:27017/Etudiant
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    

