apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.backendRepository }}:{{ .Values.image.backendTag }}"
          ports:
            - containerPort: {{ .Values.service.backendPort }}
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongodb:{{ .Values.mongodb.service.port }}/Etudiant"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
