apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.backendPort }}
      targetPort: {{ .Values.service.backendPort }}
  selector:
    app: backend
